music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/<album-id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name="album-add"),

    # /music/album/3/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album-update"),

    # /music/album/2/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name="album-delete"),

]

newproj1/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse("music:detail", kwargs={"pk": self.pk})
    

    def __str__(self):
        return self.album_title + "-" + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Album
from django.urls import reverse_lazy

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html' 


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %}Add a new Album{% endblock title %}

{% block body %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7" >
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </div>

    </div>

{% endblock body %}

music/templates/music/base.html
<head>
    <title>{% block title %}Musitory{% endblock title %}</title>

    {% load static %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '..\static\music\style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        

    

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Musitory</a>
        
            </div>
    
            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
    
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                            Albums
                        </a>    
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                            Songs
                        </a>    
                    </li>
                </ul>
    
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div> 
                    <button type="submit" class="btn btn-default">Search</button>                
                </form>
    
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Album
                        </a>    
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Logout
                        </a>    
                    </li>
                </ul>
    
            </div>
    
        </div>
    </nav>

    
    {% block body %}
        
    {% endblock body %}
        
</body>

music/templates/music/details.html
{% extends 'music/base.html' %}

{% block title %}Details{% endblock title %}

{% block body %}
    <img src="{{ album.album_logo }}" width="500px" height="500px">

    <h1>{{album.album_title}}</h1>
    <h3>{{ album.artist }}</h3>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}
            </label><br>
        {% endfor %}

        
{% endblock body %}
    </form>

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

    </div>
    
{% endfor %}
    

music/templates/music/index.html
<!-- Loads the path to your static files -->
{% extends 'music/base.html' %}






{% block body %}
    {% if all_albums %}
        <h2>This is the list of Albums</h2><br>
        
        <div class="container-fluid">
            <div class="row">
                {% for album in all_albums %}
                    <div class="col-sm-1 col-sm-offset-2">
                        <img src="{{ album.album_logo }}" width="100px" height="100px">

                        
                        <h3>{{ album.artist }}</h3>
                        <h4>{{ album.genre }}</h4>
                        <!-- Details -->
                        <a href="{%url 'music:detail' album.id %}" class="btn btn-primary">{{album.album_title}}</a><br><br>

                        <!-- Delete -->
                        <form action="{% url 'music:album-delete' album.id %}" method="POST" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}">
                            <button type="submit" class="btn btn-sm btn-danger">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                        <form action="#" method="POST" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}">
                            <button type="submit" class="btn btn-sm btn-danger">
                                <span class="glyphicon glyphicon-adjust"></span>
                            </button>
                        </form>
                    </div>
                {% endfor %}
            </div>            
        </div>

        
    {% else %}
        <h3>You Dont have any albums</h3>    
    {% endif %}    
{% endblock body %}